export const actionTypes={   
    GET_SURVEY : 'GET_SURVEY',
    GET_SURVEY_SUCCESS : 'GET_SURVEY_SUCCESS',
    GET_SURVEY_FAILURE : 'GET_SURVEY_FAILURE',

    SAVE_SURVEY_RESPONSE:"SAVE_SURVEY_RESPONSE",
    SAVE_SURVEY_RESPONSE_SUCCESS:"SAVE_SURVEY_RESPONSE_SUCCESS",
    SAVE_SURVEY_RESPONSE_FAILURE:"SAVE_SURVEY_RESPONSE_FAILURE",
}